// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about a cryptocurrency mining event observed on the monitored
/// resource.
public struct CryptoMiningEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// VM and zone in which cryptocurrency mining occurred.
  /// Format: projects/{project}/zones/{zone}/instances/{instance}
  public var vmResource: [Swift.String] = []

  /// Detected start time of the cryptocurrency mining.
  public var detectedMiningStartTime: GoogleWKT.WKTTimestamp? = nil

  /// Detected end time of the cryptocurrency mining.
  public var detectedMiningEndTime: GoogleWKT.WKTTimestamp? = nil

  /// The IP address(es) of the VM associated with the cryptocurrency mining.
  /// This field may be empty if this information is not available.
  public var vmIp: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CryptoMiningEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CryptoMiningEvent().with { $0.vmResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vmResource = CodingKeys(stringValue: "vmResource")
    static let detectedMiningStartTime = CodingKeys(stringValue: "detectedMiningStartTime")
    static let detectedMiningEndTime = CodingKeys(stringValue: "detectedMiningEndTime")
    static let vmIp = CodingKeys(stringValue: "vmIp")

    static let _knownKeys: Set<Swift.String> = [
      "vmResource",
      "detectedMiningStartTime",
      "detectedMiningEndTime",
      "vmIp",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .vmResource) {
      self.vmResource = value
    }
    self.detectedMiningStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .detectedMiningStartTime)
    self.detectedMiningEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .detectedMiningEndTime)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .vmIp) {
      self.vmIp = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.vmResource, forKey: .vmResource)
    try container.encodeIfPresent(self.detectedMiningStartTime, forKey: .detectedMiningStartTime)
    try container.encodeIfPresent(self.detectedMiningEndTime, forKey: .detectedMiningEndTime)
    try container.encode(self.vmIp, forKey: .vmIp)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `CryptoMiningEvent`: `"type.googleapis.com/google.cloud.abuseevent.logging.v1.CryptoMiningEvent"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.abuseevent.logging.v1.CryptoMiningEvent"
  }

  /// Initialize an instance of `CryptoMiningEvent` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.abuseevent.logging.v1.CryptoMiningEvent"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CryptoMiningEvent` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
