// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about an intrusion attempt event observed on the monitored
/// resource.
public struct IntrusionAttemptEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// VM and zone in which the intrusion attempt occurred.
  public var vmResource: [Swift.String] = []

  /// Detected start time of the intrusion attempt.
  public var detectedIntrusionStartTime: GoogleWKT.Timestamp? = nil

  /// Detected end time of the intrusion attempt.
  public var detectedIntrusionEndTime: GoogleWKT.Timestamp? = nil

  /// The IP address(es) of the VM associated with the intrusion attempt.
  /// This field may be empty if this information is not available.
  public var vmIp: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IntrusionAttemptEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IntrusionAttemptEvent().with { $0.vmResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vmResource = CodingKeys(stringValue: "vmResource")
    static let detectedIntrusionStartTime = CodingKeys(stringValue: "detectedIntrusionStartTime")
    static let detectedIntrusionEndTime = CodingKeys(stringValue: "detectedIntrusionEndTime")
    static let vmIp = CodingKeys(stringValue: "vmIp")

    static let _knownKeys: Set<Swift.String> = [
      "vmResource",
      "detectedIntrusionStartTime",
      "detectedIntrusionEndTime",
      "vmIp",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .vmResource) {
      self.vmResource = value
    }
    self.detectedIntrusionStartTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .detectedIntrusionStartTime)
    self.detectedIntrusionEndTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .detectedIntrusionEndTime)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .vmIp) {
      self.vmIp = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.vmResource, forKey: .vmResource)
    try container.encodeIfPresent(
      self.detectedIntrusionStartTime, forKey: .detectedIntrusionStartTime)
    try container.encodeIfPresent(self.detectedIntrusionEndTime, forKey: .detectedIntrusionEndTime)
    try container.encode(self.vmIp, forKey: .vmIp)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.abuseevent.logging.v1.IntrusionAttemptEvent"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
