// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Information about the leaked client credentials observed on the monitored
/// resource.
public struct LeakedCredentialEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// URI where the client credentials were found.
  public var detectedUri: Swift.String = Swift.String()

  /// Indicates the type of credential leaked.
  public var credentialType: OneOf_CredentialType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `LeakedCredentialEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LeakedCredentialEvent().with { $0.serviceAccountCredential = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serviceAccountCredential = CodingKeys(stringValue: "serviceAccountCredential")
    static let apiKeyCredential = CodingKeys(stringValue: "apiKeyCredential")
    static let detectedUri = CodingKeys(stringValue: "detectedUri")

    static let _knownKeys: Set<Swift.String> = [
      "serviceAccountCredential",
      "apiKeyCredential",
      "detectedUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .detectedUri) {
      self.detectedUri = value
    }

    var credentialType: OneOf_CredentialType? = nil
    let credentialTypeCheckAndSet = {
      if credentialType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'credentialType'"))
      }
      credentialType = $0
    }
    if let serviceAccountCredential = try container.decodeIfPresent(
      ServiceAccountCredential?.self, forKey: .serviceAccountCredential)
    {
      try credentialTypeCheckAndSet(.serviceAccountCredential(serviceAccountCredential))
    }
    if let apiKeyCredential = try container.decodeIfPresent(
      ApiKeyCredential?.self, forKey: .apiKeyCredential)
    {
      try credentialTypeCheckAndSet(.apiKeyCredential(apiKeyCredential))
    }
    self.credentialType = credentialType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.detectedUri, forKey: .detectedUri)

    if let choice = self.credentialType {
      switch choice {
      case .serviceAccountCredential(let value):
        try container.encode(value, forKey: .serviceAccountCredential)
      case .apiKeyCredential(let value):
        try container.encode(value, forKey: .apiKeyCredential)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Indicates the type of credential leaked.
  public enum OneOf_CredentialType: Codable, Equatable, Sendable {
    /// Information about leaked service accounts.
    indirect case serviceAccountCredential(ServiceAccountCredential?)
    /// Information about leaked API keys.
    indirect case apiKeyCredential(ApiKeyCredential?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.abuseevent.logging.v1.LeakedCredentialEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
